eureka:
    client:
        service-url:
            defaultZone: http://127.0.0.1:8761/eureka/
        register-with-eureka: false
        fetch-registry: false

spring:
  application:
    name: springCloud-register #注册中心

server:
  port: 8761